<footer>
  <p>
    This blog is powered by a <a href="https://github.com/andrewharvey/chronicle">patched version</a> of <a href="http://steve.org.uk/Software/chronicle">Chronicle</a>.
  </p>
  <p>
    The content on this blog by Andrew Harvey, unless otherwise noted is licensed under a <a href="http://creativecommons.org/licenses/by/3.0/au/">Creative Commons Attribution 3.0 Australia License</a>.
  </p>
</footer>
