<header class="title hero-unit">
  <div>
    <h1>
      <span><a href="/"><img class="icon" width="44" height="44" alt="avatar" src="/blog/img/avatar.jpg"/>
      tianjara.net</a> |</span>
      <span><a href="/blog"><img class="icon" width="44" height="44" alt="blog icon" src="/blog/img/blog-icon.png"/>
      Andrew Harvey's Blog</a></span>
    </h1>
  </div>
  <!-- tmpl_if name='blog_subtitle' -->
    <p class="tag-line"><!-- tmpl_var name='blog_subtitle' --></p>
  <!-- /tmpl_if -->
</header>
